### PR TITLE
Add support for generating scala traits

### PR DESCRIPTION
**Pull request by er1c**
A bit of scratching my own itch while I prototype something, but figured I'd create a PR if you're interested in it.

At a high-level, I'm interested in generating traits, and having more bespoke implementations for the models, allowing for backward compatible constructors between API versions.  However, I still want to ensure the correct shape of the implementation, so the logic is to generate a `trait` instead of a final `case class`

Example models:

```scala
package org.myapi
/**
 * A room with some properties.
 */
trait Room {
  val name: String
  val seats: Option[Int]
}
```

```scala
package org.myapi
sealed trait Pet {
  val name: String
}
object Pet {
  trait Cat extends Pet {
    val huntingSkill: String
    val name: String
  }
  trait Dog extends Pet {
    val packSize: Int
    val name: String
  }
}
```

### CODE REVIEW

**Comment by eikek** [comment]
Thank you very much! That looks neat!

**Comment by eikek** [comment]
The format check failed, would be great if you could run a `sbt fix` that should take care of that. 🙏🏼

**Comment by er1c** [comment]
@eikek thanks!  I might have a few more in the next months, it's grateful knowing its not unmaintained.

**Comment by eikek** [comment]
Thank you! 
This is not unmaintained, but otoh I don't do anything besides bug fixing and letting scala steward update stuff :-) It just does what I want, so no reason to pour in more time for me.

I wanted to do a release but apparently my pgp keys expired :/ So needs a bit more fiddling this time

**Pull request merged**
